// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Identity.Infrastructure.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Identity.Infrastructure.Database.Migrations
{
    [DbContext(typeof(IdentityModuleDbContext))]
    [Migration("20260111020516_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("IdentityModule")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventHandlerTypeName")
                        .HasColumnType("text");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId", "EventHandlerTypeName");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("InboxMessages", "IdentityModule");
                });

            modelBuilder.Entity("Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("EventPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventTypeAssemblyQualifiedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAt", "OccurredAt");

                    b.ToTable("OutboxMessages", "IdentityModule");
                });

            modelBuilder.Entity("Modules.Identity.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "EmailVerificationToken", "Modules.Identity.Domain.Users.User.EmailVerificationToken#EmailVerificationToken", b1 =>
                        {
                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<DateTime>("ExpiresAt");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(44);

                            b1.ToJson("EmailVerificationToken");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "PasswordResetToken", "Modules.Identity.Domain.Users.User.PasswordResetToken#PasswordResetToken", b1 =>
                        {
                            b1.Property<DateTime>("CreatedAt");

                            b1.Property<DateTime>("ExpiresAt");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(44);

                            b1.ToJson("PasswordResetToken");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Phone", "Modules.Identity.Domain.Users.User.Phone#Phone", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15);

                            b1.Property<string>("Prefix")
                                .IsRequired()
                                .HasMaxLength(5);

                            b1.ToJson("Phone");
                        });

                    b.HasKey("Id");

                    b.ToTable("Users", "IdentityModule");
                });
#pragma warning restore 612, 618
        }
    }
}
